package models.enums

enum class SpotifyStatus {
    NOT_STARTED,
    AUTHENTICATED,
    PLAYLIST_FETCHING,
    PLAYLIST_SELECTION,
    ARTIST_FETCHING,
    ARTIST_SELECTION,
    ALBUM_FETCHING,
    COMPLETED,
}